### ISSUE TITLE
Undefined behavior in va_start

### ISSUE THREAD

**Issue by jktjkt** [CESNET/libnetconf2#12]
Calling `va_start(X)` is undefined when the last argument has a type which is incompatible from the type that results from the [default argument promotion](http://en.cppreference.com/w/cpp/language/variadic_arguments#Default_conversions):

```
[6/27] Building C object CMakeFiles/netconf2.dir/src/messages_server.c.o
../src/messages_server.c:146:18: warning: passing an object that undergoes default argument promotion to 'va_start' has undefined behavior [-Wvarargs]
    va_start(ap, tag);
                 ^
../src/messages_server.c:126:15: note: parameter of type 'NC_ERR' (aka 'enum NC_ERROR') is declared here
nc_err(NC_ERR tag, ...)
              ^
1 warning generated.
[9/27] Building C object CMakeFiles/netconf2.dir/src/io.c.o
../src/io.c:983:18: warning: passing an object that undergoes default argument promotion to 'va_start' has undefined behavior [-Wvarargs]
    va_start(ap, type);
                 ^
../src/io.c:961:54: note: parameter of type 'NC_MSG_TYPE' (aka 'enum NC_MSG_TYPE') is declared here
nc_write_msg(struct nc_session *session, NC_MSG_TYPE type, ...)
```

I think that a most elegant fix is specifying the `NC_MSG_TYPE` enum size to be `int`; however, that's an obvious ABI break because it changes `sizeof(NC_MSG_TYPE)`.

Some workarounds are possible, including adding another tag argument just for `va_args`. However, this is impossible if a function is exported because that, too, is an ABI break.

**Comment by rkrejci** [comment]
hmm, unfortunately, this restriction is not mentioned in va_start's man page. How do you propose to set the enum size? I'm not sure it is possible since it is up to the compiler to decide for the enum size. Actually, in most cases this won't be a problem, because gcc and clang make 4B enum. Anyway, in general there can be a platform/compiler with a different enum size, so we should fix it.

btw, can you share version and setting of the compiler? I'm not able to get the same warning, maybe because the size of enum is by default same as `int`.

**Comment by jktjkt** [comment]
> How do you propose to set the enum size?

Ah, sorry, that's a C++11 feature not available in C.

> version and setting of the compiler

clang version 3.9.0 (tags/RELEASE_390/final), using ``-DCMAKE_BUILD_TYPE=debug`` with ``-fsanitize=address`` passed in ``CFLAGS``, ``CXXFLAGS`` and ``LDFLAGS``.
