### ISSUE TITLE
nc_server_destroy() slowness

### ISSUE THREAD

**Issue by gitter-runner** [CESNET/libnetconf2#146]
Hi!

I realized while closing down a netconf server that nc_server_destroy() can sometimes take up to 10 seconds to complete.

Is there a way to speed up shutting down the server, or maybe there's something else that might be prolonging this function?

Thanks!

**Comment by michalvasko** [comment]
Hi,
I have no idea why it could take such a long time. It does quite a lot of work but it is all freeing *libnetconf2*, *libssh*, and *libssl*/*libcrypto* data. The only possible waiting occurs in `nc_server_del_endpt()` function that is called because binds lock and endpoint write lock is required there.

Generally, you should call that function only when the server is shutting down and you have only the last thread running because if you do not, it may be possible for other threads to starve it. You can verify this, for example, by using a debugger to stop your server when this function is being waited for and you should see some other thread holding the required locks with some other ones also waiting for them.

Regards,
Michal
