### ISSUE TITLE
How to manage port 830 behind a firewall

### ISSUE THREAD

**Issue by basfrever** [CESNET/libnetconf2#179]
Hi Michal,

My Libnetconf2 server is running on port 830. Only port 22 is visible behind the firewall and Openssh  server runs on port 22(needed for other applications) .
.Is it possible to route netconf requests on port 22 to port 830. 
.If not can  we create an ssh session with openssh and pass the handle to Libnetconf2 server, for it to handle only netconf requests?
Can you suggest any better way to accomplish this.

Thanks,
pjm

**Comment by michalvasko** [comment]
Hi,
to my knowledge, you cannot do it the former way. But, it should work the latter way, by configuring your SSH server to start an application in case the `netconf` subsystem is requested. But you will have to add support for this in your *libnetconf2* server so that it somehow gets the input and output file descriptors created by the SSH server. You will then call `nc_accept_inout()` and it should work.

Regards,
Michal
