### ISSUE TITLE
Failing to find the url in nc_rpc_edit

### ISSUE THREAD

**Issue by Spoorthi-kr** [CESNET/libnetconf2#180]
Hi,

I tried using nc_rpc_edit function , 
rpc = nc_rpc_edit(NC_DATASTORE_RUNNING, 0,0,0,"dhcpd.xml",NC_PARAMTYPE_CONST);
but its throwing me a warning as:

libyang[0]: Failed to find "url" as a sibling to "ietf-netconf:target".
and this did not work even when I gave the absolute path.

What is the best way to pass the configuration?

**Comment by michalvasko** [comment]
Hi,
based on the error my guess is that you do not have `url` feature enabled in the loaded `ietf-netconf`.

Regards,
Michal

**Comment by Spoorthi-kr** [comment]
Enabled the url and treid with :
 rpc = nc_rpc_edit(NC_DATASTORE_RUNNING, 0,0,0,"file:////dhcpd.xml)
###
dhcpd.xml :-
<?xml version="1.0" encoding="UTF-8"?>
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <capabilities>
    <capability>urn:ietf:params:netconf:base:1.0</capability>
  </capabilities>
</hello>
]]>]]>
<?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <edit-config>
    <target>
      <running/>
    </target>
    <config>
      <dhcp xmlns="http://tail-f.com/ns/example/dhcpd"
            xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
        <default-lease-time nc:operation="merge">
          PT1H
        </default-lease-time>
      </dhcp>
    </config>
  </edit-config>
</rpc>
]]>]]>
<?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="2">
  <close-session/>
</rpc>
#####
Now Im getting an error like this
received a <rpc-reply> with an unexpected message-id "23"

**Comment by michalvasko** [comment]
Hi,
when trying to use *libnetconf2* directly you should be quite familiar with NETCONF and things around it. No, there are no real examples (except for the full [netopeer2](htttps://github.com/cesnet/netopeer2) server and client) but the documentation (which you have to generate using `make doc`) should be complete, it will just not tell you the general ideas and what functions to call or when to call them.

Now, you trying to use this file content for an `<edit-config>` RPC tells me you have no idea what you are doing so my suggestion is to just use `netopeer2-cli` NETCONF client instead of trying to write your own. If you insist on it, then I would at least look at our CLI code and see how exactly is a NETCONF `<edit-config>` RPC executed and try to go from there.

Regards,
Michal

**Comment by Spoorthi-kr** [comment]
The program is working now after enabling the URL and sending the right xml parameter.
Thanks :)
