### ISSUE TITLE
Single-threaded app with multiple NETCONF client sessions

### ISSUE THREAD

**Issue by manas42** [CESNET/libnetconf2#182]
Hi,

I'm trying to build a NETCONF client-side app with libnetconf2(master branch). The app will need to accept Call Home from multiple servers and establish one session with each server. I wish this app to be single-threaded, or with only 2~3 threads, since it would be running on a single or dual core platform. 
I think I should be able to send rpcs for different sessions in one single thread, right? But is it possible to handle the notifications and rpc-replys on all sessions in one single thread, like with a `select` or `epoll` mechanism? Or should I use a timer to periodically call `nc_recv_reply` and `nc_recv_notif` non-blockingly for different sessions?

Regards.

**Comment by michalvasko** [comment]
Hi,
notifications should work fine because they use a separate thread (`nc_recv_notif_dispatch()`). And you should not need to call `nc_recv_reply()` periodically, only after you send an RPC. If you want your client to be totally responsive and have a single thread then you can create your own loop and periodically call both `nc_recv_reply()` and `nc_recv_notif()` but I do not think it is worth it. 

There is no mechanism allowing passive waiting, to answer your question. However, strictly speaking, I believe nothing prevents you from creating your own *libssh* sessions with your file descriptors and passing these to *libnetconf2*, except we have never tried it. You can then probably use `select()` or `poll()` on the original file descriptors (sockets). But there is additional work required to set up your SSH sessions correctly. Also, you will not get notified only on NETCONF events but on any SSH data available on the sockets, it is not the same.

Regards,
Michal

Regards,
Michal

**Comment by manas42** [comment]
Hi,

Thank you very much for the advice. 
I believe `nc_recv_notif_dispatch()` create one thread for each session, instead of one thread to handle the notifications of all sessions? Thus if I have 72 sessions, there would still be 72 new threads?
As for the passive waiting mechanism, I'm in fact considering setting up the SSH by myself and passing the fd to libnetconf2. However, I assume in this case `nc_accept_callhome()` would be unavailible for me, and I'll have to handle the Call Home procedure by myself, is that correct?

Regards.

**Comment by manas42** [comment]
By the way, I found the issue https://github.com/CESNET/libnetconf2/issues/39 and want to know whether this feature has been implemented. Is it possible now to send multiple rpcs and call `nc_recv_reply()` multiple times to get the replys?

**Comment by michalvasko** [comment]
Hi,
that is all correct, we have simply not considered such a use-case, just simple NETCONF clients. However, the way I see it all you need is a function to get file descriptor from a NETCONF session and you can use standard *libnetconf2* functions including `nc_accept_callhome()`, right?

As for the issue, it was not implemented but briefly looking at the code it would be quite simple to add because there already is a mechanism for storing RPC replies when notifications are received instead and vice versa.

Finally, note that there is no locking mechanism on sessions themselves on NETCONF level (only on IO level) so using a single session in several threads is currently not possible.

Now, except for the last problem, all the other ones are quite simple to fix. The last one just needs a bit of design work and decide how to allow multi-threaded clients (server has its pollsession structures). I can take a look at all this but not right now. You can try to implement it yourself and I will be happy to review any pull requests.

Regards,
Michal
