### ISSUE TITLE
libssh version checking

### ISSUE THREAD

**Issue by apropp-molex** [CESNET/libnetconf2#216]
Hi,

It appears downloaded tar archives from [libssh](https://www.libssh.org/files/) don't carry up to date version information. For example, a download of 0.9.3 will say it's 0.8.90. Is this a libssh issue or are there other ways to check for the version?
As an aside, what's faulty about libssh 0.9.3 and which version is safe to use?

**Comment by michalvasko** [comment]
Hi,
the current `master` of *libssh* should work fine because the bug was fixed. So, any version except the official 0.9.3 release should be fine, currently. And the problem was that when reading the `hello` message, the function times out instead of returning the data, which breaks the whole *libnetconf2*.

Regards,
Michal

**Comment by apropp-molex** [comment]
Hi Michal,

 I'll carry on using the current `master` of `libssh` then. Thanks for your input.
