### ISSUE TITLE
nc_rpc_subscribe(), "notifications" schema in the context

### ISSUE THREAD

**Issue by DubHokku** [CESNET/libnetconf2#218]
Hello, glad to use libnetconf2. I am trying to execute the following code:

```
struct nc_rpc* rp_request = nc_rpc_subscribe( stream, filter, starttime, stoptime, NC_PARAMTYPE_CONST );
msg = nc_send_rpc( rp_session, rp_request, timeout, &msgid );
```
    
upon execution of which I get the message "missing 'notifications' schema in the context.", and msg contains NC_MSG_ERROR.

    `nc_verbosity( verbose );`
Connection setup and authentication succeed,
 ```
<capabilities>
  <capability>urn:ietf:params:netconf:base:1.0</capability>
  <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
  <capability>urn:ietf:params:netconf:capability:validate:1.0</capability>
  <capability>urn:ietf:params:xml:ns:netconf:base:1.0</capability>
  <capability>urn:ietf:params:xml:ns:netconf:capability:candidate:1.0</capability>
  <capability>urn:ietf:params:xml:ns:netconf:capability:validate:1.0</capability>
  <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring</capability>
  <capability>http://xml.juniper.net/netconf/junos/1.0</capability>
  <capability>http://xml.juniper.net/dmi/system/1.0</capability>
</capabilities>..
```
  

When setting up a session from the console ( ssh server -p 830 -s netconf ) and sending 
`<rpc message-id="1" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><get-subscribers/></rpc>`
    
the server responds:
```
...
<subscriber junos:style="count">
  <number-of-subscribers>0</number-of-subscribers>
  <number-of-active-subscribers>0</number-of-active-subscribers>
</subscriber>
...
```

I will glad if you tell me with an understanding of the _ly_context_ and the implementation of arbitrary rpc using nc_rpc_act_generic();.

--
Regards,
Hokku

**Comment by michalvasko** [comment]
Hi,
the first error is because you are trying to create a `create-subscription` RPC that is defined in the *notifications* YANG module. I think you wanted to create some custom RPC defined in those Juniper modules so yes, you should use `nc_rpc_act_generic()`. For it you need to create a data tree of the RPC using *libyang* API. The simplest way is using `lyd_new_path()` to create the whole tree when called repeatedly. You should be able to learn how to do that now on your own, it is all part of *libyang* API.

Regards,
Michal

**Comment by DubHokku** [comment]
Thanks for the advice on nc_rpc_act_generic (), I will use it. But in this case, there was an attempt to complete the subscription defined in Request for Comments 5277, for which no additional models are needed. In this case, should I form an rpc object (nc_rpc_suscribe ()) and send using nc_send_rpc ()?

--
Regards,

**Comment by michalvasko** [comment]
Hi,
the *notifications* YANG module is needed like I said. There is no YANG module in the RFC because back then there was no YANG but they were written later. The one you are looking for (with the definition of `create-subscription` RPC) can be found [here](http://www.netconfcentral.org/modulereport/notifications), for example.

Regards,
Michal

**Comment by DubHokku** [comment]
big thanks for your work, will try

Regards,
