### ISSUE TITLE
Sessions are still established but client disconnected?

### ISSUE THREAD

**Issue by foxge** [CESNET/libnetconf2#231]
Hi
I have a netconf2(1.1.7) server with ssh-0.9.0, the client has connected to server, but the ssh sessions are still established when the client application has  restarted.

I setup 4 threads on polling the max 6 sessions.

why so ?

**Comment by michalvasko** [comment]
Hi,
could you please be more verbose? You connected to the server, then disconnected (for whatever reason) and you see that the TCP session is still established? Because I do not know about any way of checking directly whether an SSH session is running, you either have a NETCONF session or only a TCP one.

Regards,
Michal

**Comment by foxge** [comment]
Hi
Other netconf client device is accessing to my netconf server, when slave switch client device, the old sessions didn't disappear via netstat command. But for old version 1.0.r2, the sessions are not present.

By the way, may you tell me the status of the sessions above？ or what difference between the two versions about the nc_ps_poll related ?

Thanks.

**Comment by michalvasko** [comment]
Hi,
you did not help me much but what you are saying is that when you disconnected with the NETCONF client, `netstat` (which prints information only about TCP connection in this case) was still showing the connection? How did you disconnect? What was the TCP session state?

Also, I do not know about any 1.0-r2 release of any of our projects. As for your last question, I am not sure what you are asking but I can try to explain. First, a TCP session is established that is fully managed by kernel (that is also the reason why only these sessions can be printed by system tools). *libnetconf2* then creates an SSH session and then NETCONF session on the TCP one. And you will, again, have to be more specific as to what you want to know about `nc_ps_poll` because I have not understood that at all.

Regards,
Michal
