### ISSUE TITLE
Data race in test_fd_comm

### ISSUE THREAD

**Issue by syyyr** [CESNET/libnetconf2#253]
Hi, TSan found some data races in `test_fd_comm`: https://gist.github.com/syyyr/a8576913bdaf7bf1e9b02e8c00d57cf2
To reproduce, just run the test with tsan.

I'm not able to debug this, so l'd be glad if you could look at this. Thanks.

**Comment by michalvasko** [comment]
When compiled with `-fsanitize=thread` I got only the first warning, which should now be fixed. Not sure what to do about the rest.

**Comment by syyyr** [comment]
I tried the new version and I'm unable to compile it on Clang. I'm seeing the same errors as in https://travis-ci.org/github/CESNET/libnetconf2/jobs/725254081 :/

**Comment by syyyr** [comment]
Okay, the reason is that atomics need C11 standard and clang does something else by default I guess. Adding `set(CMAKE_C_STANDARD 11)` to CMakeLists.txt solved the issue. This could also probably be added just for the single test

**Comment by michalvasko** [comment]
Okay, it seems to be working when I simply removed the cast to the atomic type. But you are right, C11 should be required for these atomics. However, we cannot require it because of older compilers that are still used to compile this library.

So, I would keep it this way as long as there are no problems with it. If there are, I will revert this change back and keep the `volatile` pointer. Based on my research some time ago, it is safe to be used this way despite not being required by the standard. Because before C11 there were no atomics and everyone used `volatile` so the compilers support it.

**Comment by syyyr** [comment]
Thank you for the fix, compilation works for me now. The warnings are also gone. I'm closing this issue.
> ... it is safe to be used this way...

Well, it is safe, until a guy runs your tests with TSan and reports a bug. 😁
`volatile` does not guarantee any kind of synchronization, I don't know why you would use `volatile` instead of atomic types (or some other kind of synchronization).

Anyway, setting `CMAKE_C_STANDARD` to `11` should be fine, as long as you don't set `CMAKE_C_STANDARD_REQUIRED` to `true`. CMake has some sort of a "decay" mechanism, where if it can't use `gnu11` it goes back to `gnu99` and then to `gnu90`.

At the very least, I would recommend using the `CMAKE_C_STANDARD` instead of `add_compile_options` to set the standard. I'll make a PR with CMake cleanups when I get time.

**Comment by michalvasko** [comment]
I have just explained why I would use `volatile` instead of atomics, backwards compatibility. Also, any warnings generated by `valgrind` or the sanitizers are bugs in the majority of cases but not in all (such as this one). Finally, please do not make any pull request, `CMAKE_C_STANDARD` was added in cmake 3.1, we do not want to increase the required version.

**Comment by syyyr** [comment]
So what you're saying is TSan reported a false positive and the code in question doesn't need any kind of synchronization? If that's the case, then thank you for explaining. If synchronization IS required and atomics are not available, you could use some other kind of synchronization primitive (like mutex).

About the CMake stuff: I understand, I won't make any PRs.

**Comment by michalvasko** [comment]
> So what you're saying is TSan reported a false positive and the code in question doesn't need any kind of synchronization? If that's the case, then thank you for explaining.

What I am saying is that, to my knowledge, using `volatile` variable as an atomic with relaxed memory order should be safe. However, it is not safe according to the C standard and that is why it is reported by TSan. But, I would not really consider it a false positive, I would just fall back to using it if needed because in practice there should be no problems.

**Comment by syyyr** [comment]
I guess our views on following the C standard are different. 😀 That's OK.
