### ISSUE TITLE
Failed to get the IP address from ssh

### ISSUE THREAD

**Issue by DineshReddyK** [CESNET/libnetconf2#297]
Hi,
For adding audit logs, we are patching libnetconf2 in our product.
we need to log information like server/client IP and Port.
To get the server IP and port, tried to use the following APIs, but they give empty IP and  22 port always.

```
ssh_options_get(session->ti.libssh.session, SSH_OPTIONS_HOST, &host)
ssh_options_get_port(session->ti.libssh.session, (unsigned int *)&port);
```

also tried to fetch the IP using the socket that we have, still no use.

```
fd = (session->ti_type == NC_TI_FD) ? session->ti.fd.in : session->ti.unixsock.sock
getsockname(fd, (struct sockaddr *) &my_addr, &len);
inet_ntop(AF_INET, &my_addr.sin_addr, myIP, sizeof(myIP));
```

Do you think, we need to set the host when the session is opened using `ssh_options_set` ourselves in libneconf2?
or is there any better way to get this information?

**Comment by michalvasko** [comment]
Well, `ssh_options_*` only writes/reads any options, statically I mean, you can read back only what you set (or has some defaults). But you should be able to use `nc_session_get_host()` and `nc_session_get_port()`, why are you not using those?

**Comment by DineshReddyK** [comment]
`nc_session_get_host` gives the client IP right, we needed server IP. 
Also in case of  call-home netopeer is connecting on random port right, so how can I get that information.

**Comment by michalvasko** [comment]
Right, there is no support for many of these addresses because it was not needed. However, it should first be made clear what are all the possible addresses.

You always have a bound socket A that listens on some address(es). When it accepts a connection, a new socket B is created that can be used for the actual communication. So, there is the listening address of socket A (1), the connected local address of socket B (2) and connected remote address of socket B (3). The address meaning both the IP address and port.

Address 1 and 2 can be the same in case the socket was bound to a specific address. But if, for example, the server listens on `0.0.0.0:830`, these addresses will not be the same (IP address, the port must be the same) because the connection will be made on a specific interface.

Having cleared it a bit, the function `nc_session_get_host()` and `nc_session_get_port()` should provide address 3. Address 1 can be read from the server configuration and not sure if from anywhere else, maybe. And I would guess address 2 should be possible to be retrieved from the connected socket somehow (the transport sockets stored in the session, depending on the transport you may need to get them from the SSH/TLS session). I do not know any more details and it seems useless for me to look it up if it is what you can simply do.

**Comment by DineshReddyK** [comment]
Thanks for the detailed information.
So the socket that I am getting using `fd = (session->ti_type == NC_TI_FD) ? session->ti.fd.in : session->ti.unixsock.sock` is actually the address 2 which is local. Now this is clear.
