### ISSUE TITLE
Correspondence of NETCONF Capability

### ISSUE THREAD

**Issue by zhoulinghua** [CESNET/libnetconf2#32]
hi，I just learned libnetconf2 library. so I do not know how to make it support：
writable-running
:candidate
:confirmed-commit:1.1

can you help me？thanks！

**Comment by rkrejci** [comment]
Hi, libnetconf2 provides transport so it does not implement none of these extensions (since they are connected with the datastore implementation), but it shouldn't avoid them in any way. libnetconf2 uses libyang to represent NETCONF RPCs, so it is necessary to have `ietf-netconf` schema with enable particular features in the libyang context used by libnetconf2.

**Comment by zhoulinghua** [comment]
Thanks! It needs to call lys_features_enable to implement activation.
