### ISSUE TITLE
Extracting the XPATH for a "get" or "get-config".

### ISSUE THREAD

**Issue by sterlite-del** [CESNET/libnetconf2#324]
Hi,

I wrote a small netconf server using the libnetconf2 library and API.

I am using netopeer2-cli and from it I first connect and then execute the following command:
> get --filter-xpath /a/b/c

On the server, my global RPC callback is getting called alright but in it I want to extract the XPATH passed by the client.
I tried to search the netopeer2-server code but couldn't understand how to do so. My attempts with the APIs lyd_find_xpath
and lyd_get_value are failing.

Can someone guide me with the API usage for extracting the XPATH from a lyd_node data structure ?

Thanks in advance!

**Comment by sterlite-del** [comment]
Just to clarify, I tried the lyd_find_xpath and lyd_get_value APIs in the following manner in the global RPC callback:
    _struct ns_user_sess *user_sess;
    struct nc_server_reply *reply = NULL;
    struct ly_set *st;

    /* get this user session with its originator data, no need to use ref-count */
    user_sess = nc_session_get_data(ncs);

    lyd_find_xpath(rpc, "*", &st);

    printf("kc: %s\n",lyd_get_value(st->dnodes[0]));_

**Comment by michalvasko** [comment]
When you receive an RPC, it is in a tree format (`struct lyd_node`) representing the particular RPC such as [get](https://github.com/CESNET/netopeer2/blob/master/modules/ietf-netconf%402013-09-29.yang#L742). In it, there is a `filter` anyxml node that you need to examine to find the subtree/xpath filter used. You get the child of the top-level RPC node (`lyd_child()`) and look at its metadata (`meta` attribute of `struct lyd_node`) because that is how the filter is [encoded](https://datatracker.ietf.org/doc/html/rfc6241#section-7.7). Note that writing your own NETCONF server is not trivial and I am not able to help with every single feature you will want to add.

**Comment by sterlite-del** [comment]
okay thank you. closing this issue.
