### ISSUE TITLE
nc_connect_ssh failed when there was an assertion in retrieve_schema_data_getschema

### ISSUE THREAD

**Issue by onghoaibao** [CESNET/libnetconf2#357]
I have case like this: 
My server does not has ietf-yang-metadata, but I have tried to connect to server, I got a exception like this:
![image](https://user-images.githubusercontent.com/47877762/148633128-9c3e254b-656b-4f80-b900-62df1b86683f.png)
Do you know how to fix this?
Thank everyone.

**Comment by michalvasko** [comment]
What *libyang* version are you using? Are you able to provide the full stack trace (using `gdb` or `valgrind`)?

**Comment by onghoaibao** [comment]
I'm using the last version for libyang.
this gdb:
![image](https://user-images.githubusercontent.com/47877762/148736171-7d8ba46d-41c6-4db5-b882-ae53940d1764.png)

**Comment by onghoaibao** [comment]
I can connect successful when I do this:
![image](https://user-images.githubusercontent.com/47877762/148737020-53117b53-020d-46c7-881b-010e4fc846ce.png)
in session_client.c

**Comment by michalvasko** [comment]
It is difficult for me to test so please apply this [patch](https://github.com/CESNET/libnetconf2/files/7837637/fix.patch.txt) to *libyang* and try again, let me know if it works fine.

**Comment by onghoaibao** [comment]
it can connect successfully but it has this error.
![image](https://user-images.githubusercontent.com/47877762/148740536-277e71ef-e115-4b6d-9be7-a435f0ab8c6f.png)

Thanks.

**Comment by michalvasko** [comment]
Fine, that is expected. But I am still puzzled by the fat that `ietf-yang-metadata` is being loaded as an import of `ietf-netconf`, which should not import this module.

**Comment by onghoaibao** [comment]
I think you should fix this in libnetconf2.
**in the session_client.c:** 
I think you should remove the **retrieve_schema_data_getschema()** **at the line 570**. because if match = false then mod_name does not exist in user_data which means yang module is not found in server.
so if you try to **retrieve_schema_data_getschema()** it will raise an error as the title says. 
To fix this you should remove **retrieve_schema_data_getschema()** and just using **retrieve_schema_data_localfile()**
like this:
![image](https://user-images.githubusercontent.com/47877762/148886689-72304fcb-5cf4-4938-9d9f-7f6df58af1a7.png)

I have fixed this then it work fine.
Thanks.

**Comment by michalvasko** [comment]
You seem to be certain to know what to do despite clearly not understanding the problem so please let the solution up to me. I have figured out why the module `ietf-yang-metadata` is being loaded, it is caused by internal import of this module because it is necessary for full `ietf-netconf` support. The metadata are used for operations defined on nodes in `edit-config` content, which would not be supported without the module.

It is true that initially, when `edit-config` was specified there were no metadata so `operation` was defined ad-hoc for this particular use but that was a long time ago. In case you are connecting to such an old server, you will see those few errors, which will not affect functionality, though. If you really want to, I could change the error to warning and/or improve the message to include some details.

**Comment by onghoaibao** [comment]
I understand the problem, if possible please change the error to warning.
Thank you so much for providing me with the information.
