### ISSUE TITLE
close ssh timeout

### ISSUE THREAD

**Issue by dronord** [CESNET/libnetconf2#362]
Hello.
I have Fedora linux x64 and
libssh-0.9.6-1
libyang-2.0.112
libnetconf2-2.0.24

My program do nc_connect_ssh(by pass) and next nc_session_free().
While closing successful connection, i get pause for ~15s and errors after:
Session 3894 [ERR]: Inactive read timeout elapsed.
Session 3894 [ERR]: Invalid session to write to.
Session 3894 [ERR]: Invalid session to read from.
Session 3894 [ERR]: Failed to receive a reply to <close-session>.

Can i close session without timeout and errors?

Sorry, i want ask you.
1. Which .yang files needed to get & set interfaces info+state?
2. On Centos 8 i cant compile libnetconf2, incompatible libssh version 0.9.4 What to do?

**Comment by michalvasko** [comment]
> Can i close session without timeout and errors?

Based on the error I believe the other end does not behave as it should, it does not reply properly to `<close-session>`.

> Which .yang files needed to get & set interfaces info+state?

I assume you are talking about `ietf-interfaces` YANG module. But you do not need just the YANG modules for the interfaces configuration to work, you would have to actually implement it. Our tools just provide a framework that make it as easy as possible.

> On Centos 8 i cant compile libnetconf2, incompatible libssh version 0.9.4 What to do?

Not sure if there are some non-standard repositories with a newer version, you can try to find some. Otherwise you will have to compile and install a newer version yourself. *libssh* 0.9.4 is buggy and would result in some errors when connecting.
