### ISSUE TITLE
The option 'ENABLE_PYTHON' of libnetconf2 CMakeLists.txt

### ISSUE THREAD

**Issue by karnyang** [CESNET/libnetconf2#408]
Hi, I follow the libnetconf2 installation steps, But when I run the python3 backend/, an error 'cannot find netconf2'
$ git clone -b devel https://github.com/CESNET/libnetconf2
$ mkdir -p libnetconf2/build && cd libnetconf2/build
$ cmake -DENABLE_PYTHON=ON ..
This option 'ENABLE_PYTHON' is not available in the CMakeLists.txt. so netconf2 is not compiled.
I want to know how to solve it, thanks!

**Comment by michalvasko** [comment]
Where did you find the `ENABLE_PYTHON` option? If you are simply using from the previous version, the bindings were removed from *libnetconf2* a long time ago because they were not maintained and incomplete. All the bindings for our libraries are now separate projects developed by third-parties. It seems that Python bindings for *libnetconf2* are pretty much the only bindings that no one cared to implement so it seems there is no demand for them. In summary, it seems they are not available.

**Comment by SmiVan** [comment]
Different person, but I can tell you where I found that option, in the build instructions for Netopeer2GUI v2:
https://github.com/CESNET/Netopeer2GUI/tree/v2

I would greatly appreciate it if you could inform me which is the last tag that supported that, if its no longer supported.

**Comment by michalvasko** [comment]
Yes, netopeer2GUI is obviously not supported for several years while the development of *libnetconf2* and the other libraries continues.
