### ISSUE TITLE
netopeer2-cli

### ISSUE THREAD

**Issue by cigdem123** [CESNET/libnetconf2#410]
Hi,
How can I run server.c in netopeer2-cli or yangcli ?

**Comment by michalvasko** [comment]
Um, what? Sorry, but I am not able to ask anything more specific to understand what you are asking.

**Comment by cigdem123** [comment]
sorry, i want to run this code in yangcli or netopeer2-cli client

**Comment by michalvasko** [comment]
What code? The only `server.c` source file is of a simple example NETCONF server, what connection does it have to `yangcli` or `netopeer2-cli`, how can either of them "run" it?

**Comment by cigdem123** [comment]
i want to use netopeer or yangcli as client, these are installed.

**Comment by michalvasko** [comment]
Oh, you want to **connect** to the example server using those clients. That is not a particularly good idea because almost no RPCs are implemented but it should work if you start the server with `--ssh <host-key>` parameter so that it is listening for SSH connections. Then just connect to it on `localhost`.

**Comment by cigdem123** [comment]
thank you very much
