### ISSUE TITLE
Missing dependencies in package detection

### ISSUE THREAD

**Issue by RaitoBezarius** [CESNET/libnetconf2#464]
Hi there, thank you for the amazing library.

I'm packaging the Netopeer2 suite in Nixpkgs/NixOS and I realized there were two hidden dependencies: PCRE2 (from libyang) and libxcrypt (for `crypt.h`).

I think it would make packaging easier to list them in the CMake machinery

**Comment by michalvasko** [comment]
Glad you appreciate it and I have added `crypt` to dependencies in the README, not sure what else to do. It should be expected that if a project depends on another, which then depends on some other project, then the first depends also on the third, dependencies are transitive, obviously. This does not have to mentioned explicitly because *netopeer2* or *libnetconf2* do not directly use PCRE2.
