### ISSUE TITLE
query on host key calllback

### ISSUE THREAD

**Issue by kr234** [CESNET/libnetconf2#506]
Hi Team,

    In libnetconf2 3.3.3 observe that the host key check callback api(nc_client_ssh_ch_set_auth_hostkey_check_clb)  is not available. Any specific reason for this?

**Comment by Roytak** [comment]
Hello, the callback was removed, because we wanted to have hostkey checks similar to the ones described in `man ssh_config`. So the callback was replaced by two new API - `nc_client_ssh_set_knownhosts_mode` and `nc_client_ssh_set_knownhosts_path`. That being said, I just found out that the Call Home variants of these new APIs are missing, so that needs to be fixed.

Are these 2 new APIs going to be sufficient for you? Or is there something else you'd need the callback for?
